use std::collections::BTreeSet;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

const MIN_WORD_LEN: usize = 2;

fn repo_root(manifest_dir: &Path) -> PathBuf {
    manifest_dir
        .join("../..")
        .canonicalize()
        .expect("repo root")
}

fn google_word_list(repo_root: &Path) -> PathBuf {
    repo_root.join("vendor/google-10000-english/google-10000-english.txt")
}

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let manifest_path = Path::new(&manifest_dir);
    let root = repo_root(manifest_path);
    let data_dir = root.join("data");

    let google_words = google_word_list(&root);
    if !google_words.is_file() {
        panic!(
            "missing {} — run: git submodule update --init --recursive",
            google_words.display()
        );
    }

    // data/english_words.txt supplements vendor list; BTreeSet dedupes overlaps before PHF codegen.
    let word_files = [data_dir.join("english_words.txt"), google_words];

    let mut words = BTreeSet::new();
    for path in &word_files {
        println!("cargo:rerun-if-changed={}", path.display());
        let raw = fs::read_to_string(path).unwrap_or_else(|_| {
            panic!("read word list {}", path.display());
        });
        for line in raw.lines() {
            let word = line.trim().to_ascii_lowercase();
            if word.len() >= MIN_WORD_LEN && word.chars().all(|c| c.is_ascii_alphabetic()) {
                words.insert(word);
            }
        }
    }

    let mut phf_set = phf_codegen::Set::new();
    for word in &words {
        phf_set.entry(word);
    }

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let out_path = Path::new(&out_dir).join("english_words.rs");
    let code = format!(
        "// @generated by build.rs — do not edit\n\n\
         /// {} entries — compile-time PHF, O(1) lookup per token.\n\
         pub static WORDS: phf::Set<&'static str> = {};\n",
        words.len(),
        phf_set.build()
    );
    fs::write(&out_path, code).expect("write english_words.rs");

    eprintln!("cm-english: compiled {} dictionary entries", words.len());
}
