use std::env;
use std::fs;
use std::path::{Path, PathBuf};

const BMP_MAX: u32 = 0xFFFF;
const BITMAP_WORDS: usize = 1024;
const NORMAL_ASCII_LEN: usize = 65536;
const BLOOM_BYTES: usize = 256;

#[derive(Debug, serde::Deserialize)]
struct AlphabetFile {
    char: Vec<CharEntry>,
}

#[derive(Debug, serde::Deserialize)]
struct CharEntry {
    codepoint: u32,
    normal: String,
    /// Documentary grouping in custom_alphabet.toml; not used at runtime.
    #[allow(dead_code)]
    category: String,
}

struct LookupTables {
    bitmap: [u64; BITMAP_WORDS],
    normal_ascii: [u8; NORMAL_ASCII_LEN],
    bloom: [u8; BLOOM_BYTES],
    supplementary: Vec<u32>,
    supplementary_normal: Vec<(u32, u8)>,
    normal_chars: Vec<(u32, char)>,
}

/// Expected repo layout: crates/cm-alphabet → ../../data/custom_alphabet.toml
fn resolve_data_path(manifest_dir: &Path) -> PathBuf {
    manifest_dir
        .join("../../data/custom_alphabet.toml")
        .canonicalize()
        .expect("custom_alphabet.toml")
}

fn parse_alphabet(data_path: &Path) -> AlphabetFile {
    let raw = fs::read_to_string(data_path).expect("read alphabet");
    toml::from_str(&raw).expect("parse alphabet")
}

fn build_lookup_tables(parsed: &AlphabetFile) -> LookupTables {
    let mut tables = LookupTables {
        bitmap: [0u64; BITMAP_WORDS],
        normal_ascii: [0u8; NORMAL_ASCII_LEN],
        bloom: [0u8; BLOOM_BYTES],
        supplementary: Vec::new(),
        supplementary_normal: Vec::new(),
        normal_chars: Vec::new(),
    };

    for entry in &parsed.char {
        let cp = entry.codepoint;
        assert!(
            entry.normal.len() == 1,
            "normal must be one char for U+{cp:04X}"
        );
        let normal = entry.normal.chars().next().unwrap();
        assert!(
            normal.is_ascii_alphabetic(),
            "normal must be ASCII alphabetic (A–Z or a–z) for U+{cp:04X}"
        );
        let ascii_byte = normal.to_ascii_lowercase() as u8;

        if cp <= BMP_MAX {
            set_bitmap_bit(&mut tables.bitmap, cp);
            tables.normal_ascii[cp as usize] = ascii_byte;
        } else {
            tables.supplementary.push(cp);
            tables.supplementary_normal.push((cp, ascii_byte));
            set_bloom(&mut tables.bloom, cp);
        }

        tables.normal_chars.push((cp, normal));
    }

    tables.supplementary.sort_unstable();
    tables.supplementary_normal.sort_by_key(|(cp, _)| *cp);
    tables
}

fn write_generated_rs(out_path: &Path, tables: &LookupTables) {
    let mut code = String::new();
    code.push_str("// @generated by build.rs — do not edit\n\n");
    code.push_str(&format_bitmap(&tables.bitmap));
    code.push_str(&format_normal_ascii_table(&tables.normal_ascii));
    code.push_str(&format_bloom(&tables.bloom));
    code.push_str(&format_supplementary(&tables.supplementary));
    code.push_str(&format_supplementary_normal(&tables.supplementary_normal));
    code.push_str(&format_normal_map(&tables.normal_chars));
    fs::write(out_path, code).expect("write alphabet_lookup.rs");
}

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let data_path = resolve_data_path(Path::new(&manifest_dir));

    println!("cargo:rerun-if-changed={}", data_path.display());

    let parsed = parse_alphabet(&data_path);
    let tables = build_lookup_tables(&parsed);

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let out_path = Path::new(&out_dir).join("alphabet_lookup.rs");
    write_generated_rs(&out_path, &tables);
}

/// BMP suspicious bitmap: 64-bit word index = cp >> 6, bit = cp & 63.
fn set_bitmap_bit(bitmap: &mut [u64; BITMAP_WORDS], cp: u32) {
    let idx = (cp >> 6) as usize;
    let bit = cp & 63;
    bitmap[idx] |= 1u64 << bit;
}

/// 256-byte bloom filter with three hash seeds derived from the codepoint.
fn set_bloom(bloom: &mut [u8; BLOOM_BYTES], cp: u32) {
    for seed in [cp, cp.rotate_left(7), cp.rotate_left(13)] {
        let h = (seed ^ (seed >> 16)) as usize;
        let idx = h % BLOOM_BYTES;
        let bit = (h >> 8) % 8;
        bloom[idx] |= 1u8 << bit;
    }
}

fn join_formatted<T, F>(items: &[T], fmt: F) -> String
where
    F: Fn(&T) -> String,
{
    items.iter().map(fmt).collect::<Vec<_>>().join(", ")
}

fn format_bitmap(bitmap: &[u64; BITMAP_WORDS]) -> String {
    let values = join_formatted(bitmap, |v| format!("0x{v:016X}"));
    format!("pub static SUSPICIOUS_BITMAP: [u64; 1024] = [{values}];\n\n")
}

fn format_normal_ascii_table(table: &[u8; NORMAL_ASCII_LEN]) -> String {
    let values = join_formatted(table, |v| v.to_string());
    format!("pub static NORMAL_ASCII: [u8; 65536] = [{values}];\n\n")
}

fn format_supplementary_normal(supp: &[(u32, u8)]) -> String {
    let cps = join_formatted(supp, |(cp, _)| format!("0x{cp:04X}"));
    let bytes = join_formatted(supp, |(_, b)| b.to_string());
    format!(
        "pub static SUPPLEMENTARY_NORMAL_ASCII: &[u32] = &[{cps}];\n\
         pub static SUPPLEMENTARY_NORMAL_BYTES: &[u8] = &[{bytes}];\n\n"
    )
}

fn format_bloom(bloom: &[u8; BLOOM_BYTES]) -> String {
    let values = join_formatted(bloom, |v| format!("0x{v:02X}"));
    format!("pub static BLOOM_FILTER: [u8; 256] = [{values}];\n\n")
}

fn format_supplementary(supp: &[u32]) -> String {
    let cps = join_formatted(supp, |cp| format!("0x{cp:04X}"));
    format!("pub static SUPPLEMENTARY_CODEPOINTS: &[u32] = &[{cps}];\n\n")
}

fn format_normal_map(entries: &[(u32, char)]) -> String {
    let cps = join_formatted(entries, |(cp, _)| format!("0x{cp:04X}"));
    let normals = join_formatted(entries, |(_, ch)| format!("'{}'", ch.escape_default()));
    format!(
        "pub static NORMAL_CODEPOINTS: &[u32] = &[{cps}];\n\
         pub static NORMAL_CHARS: &[char] = &[{normals}];\n\n"
    )
}
