//! Compile-time alphabet bitmap and canonicalization.

#![forbid(unsafe_code)]

use cm_normalize::nfkc;

// Generated by build.rs: SUSPICIOUS_BITMAP, BLOOM_FILTER, supplementary tables, etc.
include!(concat!(env!("OUT_DIR"), "/alphabet_lookup.rs"));

/// Stats from mapping suspicious alphabet chars to normalized ASCII.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct CanonicalStats {
    /// Alphabetic characters in the input.
    pub relevant: u32,
    /// Characters that hit the custom alphabet bitmap.
    pub suspicious: u32,
    /// Suspicious characters successfully mapped to ASCII via the alphabet table.
    pub converted: u32,
}

impl CanonicalStats {
    /// Share of suspicious chars that were mapped: `converted / suspicious`.
    #[inline]
    pub fn conversion_ratio(&self) -> f32 {
        if self.suspicious == 0 {
            0.0
        } else {
            self.converted as f32 / self.suspicious as f32
        }
    }

    /// Obfuscated letters as a share of all letters: `suspicious / relevant`.
    #[inline]
    pub fn obfuscation_ratio(&self) -> f32 {
        if self.relevant == 0 {
            0.0
        } else {
            self.suspicious as f32 / self.relevant as f32
        }
    }
}

/// Canonical ASCII output plus conversion counters.
#[derive(Debug, Clone, PartialEq)]
pub struct CanonicalResult {
    pub text: String,
    pub stats: CanonicalStats,
    /// Per-character flag: `true` if this output char came from an obfuscated letter.
    pub obfuscated_mask: Vec<bool>,
}

/// True when `cp` is in the custom alphabet: BMP uses O(1) bitmap lookup; supplementary
/// codepoints use bloom prefilter plus sorted binary search.
#[inline]
pub fn is_suspicious_codepoint(cp: u32) -> bool {
    if cp <= 0xFFFF {
        let idx = (cp >> 6) as usize;
        let bit = cp & 63;
        return SUSPICIOUS_BITMAP[idx] & (1u64 << bit) != 0;
    }

    if !bloom_might_contain(cp) {
        return false;
    }

    supplementary_contains(cp)
}

#[inline]
pub fn is_relevant(ch: char) -> bool {
    ch.is_alphabetic()
}

/// Map a suspicious codepoint to its canonical ASCII letter, if known.
/// Byte `0` in `NORMAL_ASCII` means unmapped.
#[inline]
pub fn normal_ascii_byte(cp: u32) -> Option<u8> {
    if cp <= 0xFFFF {
        let b = NORMAL_ASCII[cp as usize];
        return if b == 0 { None } else { Some(b) };
    }
    supplementary_normal_byte(cp)
}

/// Char wrapper around [`normal_ascii_byte`].
#[inline]
pub fn normal_char(cp: u32) -> Option<char> {
    normal_ascii_byte(cp).map(|b| b as char)
}

/// Map one normalized character to canonical output and update stats.
/// Returns `(canonical_char, was_obfuscated)`.
#[inline]
pub fn map_char(ch: char, stats: &mut CanonicalStats) -> (char, bool) {
    if is_relevant(ch) {
        stats.relevant += 1;
    }

    let cp = ch as u32;
    if is_suspicious_codepoint(cp) {
        stats.suspicious += 1;
        if let Some(ascii) = normal_ascii_byte(cp) {
            stats.converted += 1;
            return (ascii as char, true);
        }
        return (ch, true);
    }

    (ch, false)
}

/// Canonicalize already-NFKC text into reusable buffers.
/// `normalized` must be NFKC output; `obfuscated_mask` receives one flag per output char.
pub fn canonicalize_normalized_into(
    normalized: &str,
    out: &mut String,
    obfuscated_mask: &mut Vec<bool>,
) -> CanonicalStats {
    out.clear();
    obfuscated_mask.clear();
    out.reserve(normalized.len());
    obfuscated_mask.reserve(normalized.len());

    let mut stats = CanonicalStats::default();
    for ch in normalized.chars() {
        let (mapped, obfuscated) = map_char(ch, &mut stats);
        out.push(mapped);
        obfuscated_mask.push(obfuscated);
    }
    stats
}

/// NFKC + custom alphabet → normalized ASCII, with conversion stats.
pub fn canonicalize_with_stats(input: &str) -> CanonicalResult {
    let normalized = nfkc(input);
    let mut out = String::with_capacity(normalized.len());
    let mut obfuscated_mask = Vec::with_capacity(normalized.len());
    let stats = canonicalize_normalized_into(&normalized, &mut out, &mut obfuscated_mask);

    CanonicalResult {
        text: out,
        stats,
        obfuscated_mask,
    }
}

/// Replace suspicious alphabet chars with their normal ASCII forms.
pub fn canonicalize(input: &str) -> String {
    canonicalize_with_stats(input).text
}

#[inline]
fn supplementary_normal_byte(cp: u32) -> Option<u8> {
    match SUPPLEMENTARY_NORMAL_ASCII.binary_search(&cp) {
        Ok(idx) => Some(SUPPLEMENTARY_NORMAL_BYTES[idx]),
        Err(_) => None,
    }
}

/// Bloom prefilter for supplementary codepoints: `false` excludes; `true` is inconclusive.
#[inline]
fn bloom_might_contain(cp: u32) -> bool {
    for seed in [cp, cp.rotate_left(7), cp.rotate_left(13)] {
        let h = (seed ^ (seed >> 16)) as usize;
        let idx = h % 256;
        let bit = (h >> 8) % 8;
        if BLOOM_FILTER[idx] & (1u8 << bit) == 0 {
            return false;
        }
    }
    true
}

#[inline]
fn supplementary_contains(cp: u32) -> bool {
    SUPPLEMENTARY_CODEPOINTS.binary_search(&cp).is_ok()
}

#[cfg(test)]
mod tests {
    use super::*;

    const SMALL_CAPS_PHRASE: &str = "ʏᴏ ʙʀᴏ";

    #[test]
    fn bitmap_hits_small_cap_o() {
        assert!(is_suspicious_codepoint(0x1D0F));
    }

    #[test]
    fn ascii_letters_not_suspicious() {
        assert!(!is_suspicious_codepoint('a' as u32));
        assert!(!is_suspicious_codepoint('Z' as u32));
    }

    #[test]
    fn canonicalize_ascii_only() {
        let result = canonicalize_with_stats("hello stream");
        assert_eq!(result.text, "hello stream");
        assert_eq!(result.stats.relevant, 11);
        assert_eq!(result.stats.suspicious, 0);
        assert_eq!(result.stats.obfuscation_ratio(), 0.0);
    }

    #[test]
    fn canonicalize_small_caps() {
        let result = canonicalize_with_stats(SMALL_CAPS_PHRASE);
        assert_eq!(result.text, "yo bro");
        assert_eq!(result.stats.relevant, 5);
        assert_eq!(result.stats.suspicious, 5);
        assert_eq!(result.stats.obfuscation_ratio(), 1.0);
    }

    #[test]
    fn mixed_partial_obfuscation_ratio() {
        let result = canonicalize_with_stats("hellᴏ");
        assert_eq!(result.stats.relevant, 5);
        assert_eq!(result.stats.suspicious, 1);
        assert!((result.stats.obfuscation_ratio() - 0.2).abs() < f32::EPSILON);
    }

    #[test]
    fn canonicalize_maps_small_caps() {
        assert_eq!(canonicalize(SMALL_CAPS_PHRASE), "yo bro");
    }

    #[test]
    fn canonicalize_with_stats_tracks_conversion() {
        let result = canonicalize_with_stats(SMALL_CAPS_PHRASE);
        assert_eq!(result.text, "yo bro");
        assert_eq!(result.stats.suspicious, 5);
        assert_eq!(result.stats.converted, 5);
        assert_eq!(result.stats.conversion_ratio(), 1.0);
    }

    #[test]
    fn canonicalize_normalized_into_matches_with_stats() {
        // Input is NFKC-stable for this phrase (no compatibility decomposition).
        let input = SMALL_CAPS_PHRASE;
        let full = canonicalize_with_stats(input);
        let mut out = String::new();
        let mut mask = Vec::new();
        let stats = canonicalize_normalized_into(input, &mut out, &mut mask);
        assert_eq!(out, full.text);
        assert_eq!(mask, full.obfuscated_mask);
        assert_eq!(stats, full.stats);
    }

    #[test]
    fn every_toml_entry_round_trips() {
        for (cp, normal) in NORMAL_CODEPOINTS.iter().zip(NORMAL_CHARS.iter()) {
            assert!(is_suspicious_codepoint(*cp));
            assert_eq!(normal_char(*cp), Some(*normal));
        }
    }
}
