[package]
name = "optimod-checker"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "OptiMod host checker pipeline and plugin loader"
rust-version.workspace = true

[dependencies]
optimod-plugin-sdk = { workspace = true }
cm-core = { workspace = true, optional = true }
cm-english = { workspace = true, optional = true }
damsel-core = { workspace = true, optional = true }
libloading = { version = "0.8", optional = true }
tracing = { version = "0.1", optional = true }
serde_json = { workspace = true }

[features]
default = ["small_caps_obfuscation", "damsel_in_distress"]
small_caps_obfuscation = ["dep:cm-core", "dep:cm-english"]
damsel_in_distress = ["dep:cm-core", "dep:damsel-core"]
dll = ["dep:libloading", "dep:tracing"]
